import { idea as i, sounds, IdeaPools, CuratedPools } from './shared';

// Deutsch: Ideen für die Aufgaben „lesen / hören / ausprobieren“. Kulturelle Bezüge für deutschsprachige Menschen gewählt.
export const IDEAS_DE: IdeaPools = {
  read_inspire: [
    i('Du musst dich nicht bereit fühlen, um anzufangen: Bereit wird man durchs Tun. Such dir heute eine einzige kleine Handlung aus und tu sie jetzt, bevor du entscheidest, ob du Lust hast.'),
    i('Schwierige Tage löschen Fortschritte nicht aus: Sie sind der Boden, in dem Gewohnheiten Wurzeln schlagen. Heute hier zu sein, auch müde, ist mehr wert als ein perfekter Tag.'),
    i('Was dich belastet, hat oft mit dem zu tun, was dir wichtig ist. Frag dich nicht „Warum stehe ich unter Druck?“, sondern „Was versuche ich zu schützen?“.'),
    i('Sich um sich selbst zu kümmern ist kein Egoismus: So hast du mehr für andere übrig. Fünf Minuten für dich nimmst du niemandem weg.'),
    i('Kurze, warmherzige Briefe über den Mut, die eigenen Fragen zu leben, ohne gleich die Antworten zu haben. Lies auch nur einen davon.', 'Buch „Briefe an einen jungen Dichter“ von Rainer Maria Rilke'),
    i('Ganz kurze Gedanken eines Kaisers, der schrieb, um im Gleichgewicht zu bleiben. Schlag eine beliebige Seite auf und lies den ersten Gedanken.', 'Buch „Selbstbetrachtungen“ von Mark Aurel'),
    i('Ein kurzer, klarer Text darüber, wie man seine Zeit gut nutzt. Wenige Seiten genügen, um den Blick auf den Tag zu verändern.', 'Buch „Von der Kürze des Lebens“ von Seneca'),
    i('Darüber, wie man Gelassenheit findet, indem man im gegenwärtigen Moment innehält, statt alles aufzuschieben, bis alles in Ordnung ist.', 'Buch „Jetzt! Die Kraft der Gegenwart“ von Eckhart Tolle'),
    i('Über den Mut, sich unvollkommen zu zeigen. Jedes beliebige Kapitel genügt, um sich mit den eigenen Fehlern weniger allein zu fühlen.', 'Buch „Die Gaben der Unvollkommenheit“ von Brené Brown'),
  ],
  podcast: [
    i('Psychologie im Alltag, verständlich und unterhaltsam erzählt: kleine Impulse, die du sofort ausprobieren kannst.', 'Podcast „Psychologie to go!“'),
    i('Wissenschaft für unterwegs, leicht verständlich erklärt, für Momente, in denen du etwas Neues lernen möchtest.', 'Podcast „Quarks Daily“ (WDR)'),
    i('Lange, ruhige Gespräche mit interessanten Menschen über das Leben und seinen Sinn.', 'Podcast „Hotel Matze“'),
    i('Die Wissenschaft des Glücks, erklärt von einer Yale-Professorin: praktische Folgen mit kleinen Gewohnheiten zum sofortigen Ausprobieren. Auf Englisch.', 'Podcast „The Happiness Lab“ von Laurie Santos'),
    i('Meditation und Alltag, mit Humor und Ehrlichkeit erzählt, ideal, wenn du bei null anfängst. Auf Englisch.', 'Podcast „Ten Percent Happier“ mit Dan Harris'),
    i('Neurowissenschaft rund um Schlaf, Energie und Konzentration. Die Folgen sind lang: Hör ruhig nur die ersten 10 Minuten. Auf Englisch.', 'Podcast „Huberman Lab“ von Andrew Huberman'),
    i('Warum wir tun, was wir tun: Psychologie und Neurowissenschaft als Geschichten erzählt. Auf Englisch.', 'Podcast „Hidden Brain“ von Shankar Vedantam'),
  ],
  read_relax: [
    i('Kurze, fließende Seiten, perfekt zum Abschalten: 10 genügen, um zu spüren, wie der Geist langsamer wird.', 'Buch „Der kleine Prinz“ von Antoine de Saint-Exupéry'),
    i('Kurze, leichte Geschichten: eine pro Abend, ohne Druck und ohne Ehrgeiz, fertig zu werden.', 'Buch „Marcovaldo oder Die Jahreszeiten in der Stadt“ von Italo Calvino'),
    i('Ein kurzes Buch mit langsamem, ruhigem Rhythmus, das sanft in den Schlaf begleitet.', 'Buch „Der alte Mann und das Meer“ von Ernest Hemingway'),
    i('Einfache, ruhige Prosa, passend zum Tagesabschluss.', 'Buch „Siddhartha“ von Hermann Hesse'),
    i('Sehr kurze Kapitel und ein sanfter Rhythmus: Man liest es in kleinen Schlucken.', 'Buch „Seide“ von Alessandro Baricco'),
    i('Ein sanftes, hoffnungsvolles Märchen, das man seitenweise lesen kann.', 'Buch „Der Alchimist“ von Paulo Coelho'),
    i('Ein Buch, das du schon liebst, noch einmal zu lesen entspannt mehr, als ein neues zu entdecken: Such dir einen deiner Favoriten aus und lies nur 10 Seiten.'),
    i('Wenn du kein Buch zur Hand hast, ist eine Sammlung kurzer Geschichten oder Gedichte ideal: Du kannst auf jeder Seite aufhören, ohne den Faden zu verlieren.'),
  ],
  tisana: [
    i('Der Abendklassiker: heiß, ohne Zucker, langsam und ohne Bildschirme getrunken.', 'Kamille'),
    i('Zitronig und zart, wunderbar nach dem Abendessen.', 'Zitronenmelisse'),
    i('Weich und von Natur aus süß, ideal, um vor dem Schlafengehen langsamer zu werden.', 'Lindenblüten'),
    i('Ein Duft, der zum Entspannen einlädt, auch gemischt mit Kamille.', 'Lavendel'),
    i('Wenn die Verdauung etwas träge ist, hilft er, den Abend ruhig ausklingen zu lassen.', 'Fenchel'),
    i('Das Ritual zählt so viel wie das Kraut: Bereite den Tee ohne Eile zu, halte die Tasse in den Händen und trink ihn im Sitzen, ohne Handy.'),
  ],
  music_relax: [
    i('Im Bereich Klänge findest du die Sitzung „Tiefenentspannung“, Alphawellen mit 10 Hz zur Entspannung. Mach es dir mit Stereo-Kopfhörern bequem, stell 10 Minuten ein und drück Play.', 'Klänge › Tiefenentspannung', sounds('stress')),
    i('Für eine meditativere Pause: die Sitzung „Mentales Gleichgewicht“, Thetawellen mit 6 Hz. Stereo-Kopfhörer, Augen geschlossen, 10 Minuten.', 'Klänge › Mentales Gleichgewicht', sounds('equilibrio_mentale')),
    i('Die Sitzung „Zellregeneration“, Thetawellen mit 4 Hz, für eine langsame, tiefe Pause. Stereo-Kopfhörer und 10 Minuten, ohne etwas anderes zu tun.', 'Klänge › Zellregeneration', sounds('pelle')),
  ],
  hobby: [
    i('Mal ein Mandala aus oder kritzle frei: Du musst nicht zeichnen können, lass einfach die Hand laufen.'),
    i('Kümmere dich um eine Pflanze: Staub von den Blättern wischen, gießen, aus der Nähe ansehen.'),
    i('Ein Puzzle oder ein Kreuzworträtsel: Der Geist konzentriert sich auf eine einfache Aufgabe und lässt die Gedanken los.'),
    i('Spiel oder sing ein Stück, das du kennst, auch ganz leise: Die Stimme löst Anspannung mehr, als man denkt.'),
    i('Schreib ein paar Zeilen von Hand an einen Menschen, der dir wichtig ist, und sei es nur eine Karte.'),
    i('Fotografiere mit dem Handy drei schöne Dinge, die du gerade um dich herum findest.'),
    i('Koch etwas nur zum Vergnügen, auch etwas Kleines: einen Teig, ein einfaches Dessert, einen besonderen Tee.'),
  ],
  laugh: [
    i('Ganz kurze Sketche ohne Worte, die in jeder Sprache zum Lachen bringen: 5 Minuten auf YouTube genügen.', 'Mr. Bean (Sketche auf YouTube)'),
    i('Eine Westernparodie, die viele Menschen im deutschsprachigen Raum kennen, zum herzhaften Lachen.', 'Film „Der Schuh des Manitu“ (2001)'),
    i('Eine herzliche, lustige Komödie über eine Familie und ihre Eigenheiten.', 'Film „Willkommen bei den Hartmanns“ (2016)'),
    i('Stumme, geniale Komik, zärtlich und lustig: Schon eine einzige Szene hebt die Stimmung.', 'Film „Moderne Zeiten“ von Charlie Chaplin'),
    i('Absurder britischer Humor, ein Klassiker, der nie alt wird.', 'Film „Das Leben des Brian“ (1979)'),
    i('Ruf die Person an oder schreib ihr, die dich am meisten zum Lachen bringt: Schon 5 Minuten Witze sind so viel wert wie ein Film.'),
  ],
  music_energy: [
    i('Im Bereich Klänge findest du die Sitzung „Energie und Fokus“, Betawellen mit 20 Hz für Energie und Konzentration. Stereo-Kopfhörer, 10 Minuten, Play.', 'Klänge › Energie und Fokus', sounds('energia')),
    i('Wenn du einen Schubs zum Bewegen brauchst: die Sitzung „Aktive Motivation“, Betawellen mit 18 Hz. Stereo-Kopfhörer und 10 Minuten.', 'Klänge › Aktive Motivation', sounds('movimento')),
  ],
  snack: [
    i('Frisches Obst und eine kleine Handvoll Mandeln oder Walnüsse: Zucker und gute Fette zusammen, für stabilere Energie.'),
    i('Ein Becher Naturjoghurt (griechisch) mit ein paar Obststücken.'),
    i('Möhren- oder Selleriesticks mit etwas Hummus: knackig und sättigend.'),
    i('Im Ofen geröstete Kichererbsen mit einem Schuss Öl und Gewürzen: eine gesunde Variante des salzigen Snacks.'),
    i('Ein in Spalten geschnittener Apfel mit ein paar Walnüssen, leicht in der Tasche mitzunehmen.'),
    i('Eine Banane mit einem Teelöffel Erdnussmus (nur Erdnüsse, ohne Zuckerzusatz).'),
    i('Ungesalzene Nüsse in einer kleinen Dose: Die richtige Portion ist eine Handvoll.'),
  ],
  meditate_morning: [
    i('Setz dich bequem hin, mit geradem Rücken und Stereo-Kopfhörern. Starte die Sitzung „Mentales Gleichgewicht“ für 5 Minuten: Richte die Aufmerksamkeit auf den Atem und kehre jedes Mal, wenn der Geist abschweift, sanft dorthin zurück.', 'Klänge › Mentales Gleichgewicht (5 Minuten)', sounds('equilibrio_mentale', '5')),
    i('Für einen ruhigen Start in den Tag: die Sitzung „Tiefenentspannung“ für 5 Minuten. Augen zu, zähle zehn langsame Atemzüge und fang bei eins neu an, wenn du den Faden verlierst.', 'Klänge › Tiefenentspannung (5 Minuten)', sounds('stress', '5')),
    i('Für einen konzentrierten Start: die Sitzung „Energie und Fokus“ für 5 Minuten, sitzend, mit der Aufmerksamkeit auf dem Atem und auf einem einzigen Ziel des Tages.', 'Klänge › Energie und Fokus (5 Minuten)', sounds('energia', '5')),
  ],
  meditate_evening: [
    i('Gedämpftes Licht, Stereo-Kopfhörer, bequeme Haltung: die Sitzung „Tiefenentspannung“ für 5 Minuten. Entspanne Schultern und Kiefer und lass den Tag Atemzug für Atemzug los.', 'Klänge › Tiefenentspannung (5 Minuten)', sounds('stress', '5')),
    i('Bequem sitzend oder liegend: die Sitzung „Erholsamer Schlaf“ für 5 Minuten. Danach Bildschirm aus und ab zur Ruhe.', 'Klänge › Erholsamer Schlaf (5 Minuten)', sounds('sonno', '5')),
    i('Um den Tag mit ruhigem Geist zu beenden: die Sitzung „Mentales Gleichgewicht“ für 5 Minuten, mit der Aufmerksamkeit auf dem Atem und auf drei Dingen, für die du heute dankbar bist.', 'Klänge › Mentales Gleichgewicht (5 Minuten)', sounds('equilibrio_mentale', '5')),
  ],
  sport: [
    i('Geh zügig mit zwei Stöcken (auch eine vereinfachte Version): Der ganze Körper arbeitet mit, bei geringer Belastung für die Gelenke.', 'Nordic Walking'),
    i('Spring ein paar Sätze von 1 Minute Seil, mit Pausen: schnell, wirksam und zu Hause machbar.'),
    i('Langsame, fließende Bewegungen mit dem Atem: ideal für Gleichgewicht und Ruhe. Such ein 15-minütiges Video für Anfänger.', 'Tai-Chi'),
    i('Mach eine Playlist an und tanz 15 Minuten lang frei: Es ist Training, fühlt sich aber an wie Spielen.'),
    i('Eine Radtour in gemütlichem Tempo, auch nur durchs Viertel.'),
    i('Probier eine kurze Einheit dynamisches Dehnen mit einem Anfängervideo aus.'),
    i('Eine kostenlose Probestunde in etwas, das dich schon immer interessiert hat: Klettern in der Halle, Schwimmen, Tanzen.'),
  ],
  yoga: [
    i('Kostenlose Stunden für jedes Level: Such dir eine 10-minütige Anfängersitzung und folge ihr, ohne an etwas anderes zu denken. Auf Englisch.', 'YouTube-Kanal „Yoga With Adriene“'),
    i('Eine Mini-Sequenz, die auch ohne Video geht: Katze-Kuh 1 Minute, Herabschauender Hund 1 Minute, Kindhaltung 2 Minuten, stehende Vorwärtsbeuge 1 Minute. Atme in jeder Haltung langsam.'),
    i('Wenn du wenig Platz hast: Setz dich in den Schneidersitz, streck den Rücken und mach langsame Drehungen nach rechts und links, 5 Atemzüge pro Seite, dann beug dich nach vorn.'),
  ],
  recipe: [
    i('Kichererbsen (aus der Dose, gut abgespült) mit einem Schuss Öl, Rosmarin und etwas Gemüsebrühe erwärmt. In 20 Minuten fertig.'),
    i('Quinoa mit Gemüse der Saison, einem Schuss Öl und Zitronensaft. Lässt sich vorbereiten und ins Büro mitnehmen.'),
    i('Ofenomelett mit Zucchini und Zwiebel: wenige Zutaten, einfach, nahrhaft.'),
    i('Selbstgemachter Hummus (Kichererbsen, Tahin, Zitrone, Knoblauch, Öl) zu Gemüsesticks.'),
    i('Overnight Oats: Haferflocken, Joghurt und Obst am Vorabend, das Frühstück ist morgens fertig.'),
    i('Fetter Fisch aus dem Ofen (Makrele, Sardinen) mit Gemüsewürfeln und einem Schuss Öl: schnell und reich an guten Fetten.'),
    i('Kürbis-Ingwer-Suppe: Kürbiswürfel in Brühe mit einem Stück frischem Ingwer gekocht und püriert.'),
    i('Vollkornnudeln mit frischen Kirschtomaten, Basilikum und einem Löffel rohem Olivenöl: einfach, sättigend, leicht.'),
  ],
  veg: [
    i('Rohen Fenchel in dünnen Scheiben mit Orange und einem Schuss Öl: frisch und knackig.'),
    i('Grünkohl in der Pfanne mit Knoblauch und einem Schuss Wasser angebraten: in 10 Minuten fertig.'),
    i('Brokkoli aus dem Ofen mit Öl und Zitrone: Er wird knusprig und süß.'),
    i('Blumenkohl aus dem Ofen mit einer Prise Kurkuma und Pfeffer.'),
    i('Mangold mit Knoblauch und Öl geschwenkt: ein Klassiker, günstig und nährstoffreich.'),
    i('Gerösteter Kürbis in Spalten mit Rosmarin: süß und sättigend.'),
    i('Roter Radicchio kurz in der Pfanne oder auf dem Grill angebraten: leicht bitter und interessant.'),
  ],
  meal: [
    i('Die Tellermethode: die Hälfte des Tellers Gemüse, ein Viertel Eiweiß (Hülsenfrüchte, Fisch, Eier, weißes Fleisch), ein Viertel Vollkorn und ein Schuss rohes Olivenöl.'),
    i('Schnelles Mittagessen: abgespülte Hülsenfrüchte aus der Dose, Kirschtomaten, Gurke, ein Löffel Öl und Zitrone. In 5 Minuten fertig.'),
    i('Einfaches Abendessen: Rührei mit Spinat und eine Scheibe Vollkornbrot.'),
    i('Fisch aus dem Ofen mit dünn geschnittenen Kartoffeln und Zucchini: ein Blech, wenig Abwasch.'),
    i('Ein vollständiger großer Salat: Blattgemüse, ein Getreide (Dinkel, Naturreis), ein Eiweiß und eine Handvoll Samen.'),
  ],
  antiox: [
    i('Beeren (Heidelbeeren, Himbeeren, Brombeeren), frisch oder tiefgekühlt: gib sie zu Joghurt oder Frühstück.'),
    i('Spinat und dunkles Blattgemüse, roh im Salat oder angebraten.'),
    i('Granatapfel: Die Kerne passen zu Salaten und Joghurt.'),
    i('Tomaten, vor allem gekocht, mit einem Schuss Öl.'),
    i('Eine Handvoll Walnüsse: reich an guten Fetten und Polyphenolen.'),
    i('Ein Stückchen dunkle Schokolade (mindestens 70–85 % Kakao), langsam gegessen.'),
  ],
  face_massage: [
    i('Mit sauberen Fingern und trockenen Händen: Beginne in der Stirnmitte und fahre mit kleinen, langsamen Kreisen zu den Schläfen, 30 Sekunden.'),
    i('Dann von den Nasenflügeln zu den Wangenknochen und bis zu den Ohren, 30 Sekunden, mit leichtem Druck.'),
    i('Zum Schluss vom Kinn entlang des Kiefers zu den Ohren, 30 Sekunden. Beende es mit drei langsamen Atemzügen und warmen Händen auf dem Gesicht.'),
  ],
  nature: [
    i('Geh zum nächsten Park und setz dich 10 Minuten unter einen Baum, ohne Handy in der Hand.'),
    i('Geh langsam und achte auf 5 natürliche Dinge, die du sonst nicht bemerkst: ein Blatt, den Himmel, den Klang eines Vogels, eine Pflanze, das Licht.'),
    i('Ein botanischer Garten, ein Weg am Fluss oder ein Hügel in der Nähe: Schon eine halbe Stunde verändert die Stimmung.'),
    i('Das japanische Waldbaden besteht einfach darin, langsam zwischen den Bäumen zu gehen, zu atmen und sich umzusehen.', 'Shinrin-yoku („Waldbaden“)'),
    i('Wenn du selten rauskommst: Öffne das Fenster, sieh in den Himmel und lausche 5 Minuten den Geräuschen; oder kümmere dich um eine Pflanze auf dem Balkon.'),
  ],
};

export const CURATED_DE: CuratedPools = {
  energia: [
    { passage: 'Natürliches Licht in den ersten Minuten nach dem Aufwachen ist das stärkste Signal für deinen Körper: Es bringt mehr als jeder Kaffee, um die Energie des Tages einzustellen.', pointer: 'Podcast „Huberman Lab“ von Andrew Huberman' },
    { passage: 'Energie ist keine feste Menge, die sich erschöpft: Sie ist eher ein Rhythmus. Kleine, regelmäßige Pausen halten sie besser aufrecht als ununterbrochene Anstrengung.' },
  ],
  sonno: [
    { passage: 'Schlaf ist keine verlorene Zeit: Dann festigt der Körper Erinnerungen und repariert Gewebe. Heute Nacht gut zu schlafen ist schon eine Investition in dein Befinden von morgen.', pointer: 'Buch „Das große Buch vom Schlaf“ von Matthew Walker' },
    { passage: 'Immer zur gleichen Zeit ins Bett zu gehen und aufzustehen, auch am Wochenende, hilft dem Körper mehr als jede andere Schlafgewohnheit.' },
    { passage: 'Ein kühler, dunkler Raum sendet dem Gehirn dasselbe Signal wie die Nacht: Es ist Zeit, langsamer zu werden.' },
  ],
  stress: [
    { passage: 'Ein pochendes Herz vor einer Herausforderung ist kein Gefahrensignal: Es ist der Körper, der sich darauf vorbereitet, sein Bestes zu geben. Es so zu sehen verändert seine Wirkung wirklich.', pointer: 'TED-Vortrag „How to Make Stress Your Friend“ von Kelly McGonigal' },
    { passage: 'Wenn dich etwas anspannt, liegt es oft daran, dass es dir wirklich wichtig ist. Stress ist so gesehen auch ein Kompass.' },
  ],
  movimento: [
    { passage: 'Du brauchst kein perfektes Training: Ein Spaziergang im Tempo, bei dem du noch sprechen kannst, regelmäßig gemacht, zählt mehr als eine intensive, aber seltene Anstrengung.', pointer: 'Podcast „The Drive“ von Peter Attia' },
    { passage: 'Der Körper ist dafür gemacht, sich über den Tag verteilt immer ein wenig zu bewegen, nicht nur eine Stunde im Fitnessstudio: Zwischendurch aufzustehen zählt mehr, als du denkst.' },
  ],
  alimentazione: [
    { passage: 'Es gibt kein einzelnes Wunderlebensmittel: Die Vielfalt dessen, was du isst, Woche für Woche, zählt mehr als die heutige Einzelentscheidung.' },
    { passage: 'In Ruhe und ohne Ablenkung zu essen verändert, wie der Körper Hunger und Sättigung erkennt: nicht nur, was du isst, sondern wie.' },
  ],
  pelle: [
    { passage: 'Die Haut spiegelt den ganzen Körper: Schlaf, Stress und Ernährung sind enorm wichtig. Sie zu pflegen heißt, dich als Ganzes zu pflegen.' },
    { passage: 'Ausreichend zu trinken und sich vor der Sonne zu schützen bleiben von allen Gewohnheiten diejenigen mit der nachhaltigsten Wirkung auf die Haut.' },
  ],
  equilibrio_mentale: [
    { passage: 'Du musst keine zusätzliche Zeit finden: Schenk einfach etwas, das du heute ohnehin tust, deine volle Aufmerksamkeit, etwa einen Kaffee zu trinken, ohne an etwas anderes zu denken.', pointer: 'Buch „Wherever You Go, There You Are“ von Jon Kabat-Zinn' },
    { passage: 'Achtsamkeit bedeutet nicht, den Kopf leer zu machen: Sie bedeutet, wahrzunehmen, was in diesem Moment geschieht, ohne es gleich bewerten oder ändern zu müssen.' },
    { passage: 'Schon eine einzige Minute auf den Atem konzentriert ist eine vollständige Praxis, keine Vorstufe zu etwas Längerem.' },
  ],
};
