import { idea as i, sounds, IdeaPools, CuratedPools } from './shared';

// English: ideas for "read / listen / try" tasks. Cultural references chosen for English speakers.
export const IDEAS_EN: IdeaPools = {
  read_inspire: [
    i('You don\'t need to feel ready to begin: you become ready by doing. Today pick one small gesture and do it right now, before deciding whether you feel like it.'),
    i('Difficult days don\'t erase progress: they are the soil where habits put down roots. Being here today, even tired, is worth more than one perfect day.'),
    i('What weighs on you often has to do with what matters to you. Try asking yourself not "why am I under pressure?" but "what am I trying to protect?".'),
    i('Looking after yourself isn\'t selfish: it\'s how you have more to give to others. Five minutes for you are not taken from anyone.'),
    i('Short letters, written with warmth, about the courage to live your questions without having the answers right away. Read even just one.', 'Book "Letters to a Young Poet" by Rainer Maria Rilke'),
    i('Very short thoughts from an emperor who wrote to keep himself balanced. Open a page at random and read the first thought.', 'Book "Meditations" by Marcus Aurelius'),
    i('A short, clear text on how to make good use of your time. A few pages are enough to change your outlook on the day.', 'Book "On the Shortness of Life" by Seneca'),
    i('On finding serenity by pausing in the present moment, rather than putting everything off until everything is in order.', 'Book "The Power of Now" by Eckhart Tolle'),
    i('On the courage to show up imperfect. Any chapter is enough to feel less alone with your flaws.', 'Book "The Gifts of Imperfection" by Brené Brown'),
  ],
  podcast: [
    i('The science of happiness explained by a Yale professor: practical episodes with small habits to try right away.', 'Podcast "The Happiness Lab" by Laurie Santos'),
    i('Meditation and everyday life told with humour and honesty, great if you are starting from zero.', 'Podcast "Ten Percent Happier" with Dan Harris'),
    i('Conversations about courage, shame and relationships, with guests and research.', 'Podcast "Unlocking Us" by Brené Brown'),
    i('Why we do what we do: psychology and neuroscience told as stories.', 'Podcast "Hidden Brain" by Shankar Vedantam'),
    i('A doctor talking about small daily habits for feeling better, without extremes.', 'Podcast "Feel Better, Live More" by Dr Rangan Chatterjee'),
    i('Neuroscience applied to sleep, energy and focus. Episodes are long: even just the first 10 minutes is enough.', 'Podcast "Huberman Lab" by Andrew Huberman'),
    i('Slow, deep conversations about the meaning of things, for when you feel like pausing.', 'Podcast "On Being" with Krista Tippett'),
  ],
  read_relax: [
    i('Short, flowing pages, perfect for switching off: 10 are enough to feel your mind slow down.', 'Book "The Little Prince" by Antoine de Saint-Exupéry'),
    i('Short, light stories: one an evening, with no pressure to finish.', 'Book "Marcovaldo" by Italo Calvino'),
    i('A short book with a slow, quiet rhythm that leads gently towards sleep.', 'Book "The Old Man and the Sea" by Ernest Hemingway'),
    i('Simple, calm prose, suited to ending the day.', 'Book "Siddhartha" by Hermann Hesse'),
    i('Very short chapters and a gentle rhythm: you read it in small sips.', 'Book "Silk" by Alessandro Baricco'),
    i('A gentle, hopeful tale you can read a few pages at a time.', 'Book "The Alchemist" by Paulo Coelho'),
    i('Rereading a book you already loved relaxes you more than discovering a new one: choose one of your favourites and read just 10 pages.'),
    i('If you don\'t have a book at hand, a collection of short stories or poems is ideal: you can stop at any page without losing the thread.'),
  ],
  tisana: [
    i('The evening classic: hot, with no sugar, sipped slowly without screens.', 'Chamomile'),
    i('Lemony and delicate, lovely after dinner.', 'Lemon balm'),
    i('Soft and naturally sweet, perfect for slowing down before bed.', 'Linden'),
    i('A scent that invites you to relax, also lovely blended with chamomile.', 'Lavender'),
    i('If digestion is a bit slow, it helps you end the evening calmly.', 'Fennel'),
    i('The ritual matters as much as the herb: make your tea unhurriedly, hold the cup in your hands and drink it sitting down, without your phone.'),
  ],
  music_relax: [
    i('In the Sounds section you\'ll find the "Deep Relaxation" session, alpha waves at 10 Hz designed for relaxation. Get comfortable with stereo headphones, set 10 minutes and press Play.', 'Sounds › Deep Relaxation', sounds('stress')),
    i('For a more meditative break: the "Mental Balance" session, theta waves at 6 Hz. Stereo headphones, eyes closed, 10 minutes.', 'Sounds › Mental Balance', sounds('equilibrio_mentale')),
    i('The "Cellular Regeneration" session, theta waves at 4 Hz, for a slow, deep pause. Stereo headphones and 10 minutes without doing anything else.', 'Sounds › Cellular Regeneration', sounds('pelle')),
  ],
  hobby: [
    i('Colour in a mandala or doodle freely: you don\'t need to know how to draw, just let your hand go.'),
    i('Look after a plant: dust its leaves, water it, look at it up close.'),
    i('A jigsaw puzzle or a crossword: your mind focuses on one simple task and lets thoughts go.'),
    i('Play or sing a piece you know, even softly: your voice releases tension more than it seems.'),
    i('Write a few lines by hand to someone you care about, even just a card.'),
    i('Photograph three beautiful things around you right now with your phone.'),
    i('Cook something just for pleasure, even something small: a dough, a simple dessert, a special tea.'),
  ],
  laugh: [
    i('Wordless, very short sketches that make people laugh in any language: 5 minutes on YouTube is enough.', 'Mr. Bean (sketches on YouTube)'),
    i('Silent, brilliant comedy, tender and funny: even a single scene changes your mood.', 'Film "Modern Times" by Charlie Chaplin'),
    i('Absurd British humour, a classic that never gets old.', 'Film "Monty Python and the Holy Grail" (1975)'),
    i('A fast, elegant comedy classic, perfect for switching your head off.', 'Film "Some Like It Hot" (1959)'),
    i('A warm, funny little bear in a very British world, for an easy smile.', 'Film "Paddington 2" (2017)'),
    i('Call or message the person who makes you laugh the most: even 5 minutes of jokes is worth as much as a comedy.'),
  ],
  music_energy: [
    i('In the Sounds section you\'ll find the "Energy and Focus" session, beta waves at 20 Hz designed for energy and concentration. Stereo headphones, 10 minutes, Play.', 'Sounds › Energy and Focus', sounds('energia')),
    i('If you want a push to get moving: the "Active Motivation" session, beta waves at 18 Hz. Stereo headphones and 10 minutes.', 'Sounds › Active Motivation', sounds('movimento')),
  ],
  snack: [
    i('Fresh fruit and a small handful of almonds or walnuts: sugars and good fats together, for steadier energy.'),
    i('A pot of plain Greek yoghurt with a few pieces of fruit.'),
    i('Carrot or celery sticks with a little hummus: crunchy and filling.'),
    i('Oven-roasted chickpeas with a drizzle of oil and spices: a healthy take on a salty snack.'),
    i('A sliced apple with a few walnuts, easy to carry in your bag.'),
    i('A banana with a teaspoon of peanut butter (just peanuts, no added sugar).'),
    i('Unsalted nuts in a small container: the right portion is a handful.'),
  ],
  meditate_morning: [
    i('Sit comfortably with a straight back and stereo headphones. Start the "Mental Balance" session for 5 minutes: bring your attention to your breath and, every time your mind wanders, gently come back to it.', 'Sounds › Mental Balance (5 minutes)', sounds('equilibrio_mentale', '5')),
    i('To start the day calmly: the "Deep Relaxation" session for 5 minutes. Eyes closed, count ten slow breaths and start again from one when you lose count.', 'Sounds › Deep Relaxation (5 minutes)', sounds('stress', '5')),
    i('To start focused: the "Energy and Focus" session for 5 minutes, seated, with your attention on your breath and on a single goal for the day.', 'Sounds › Energy and Focus (5 minutes)', sounds('energia', '5')),
  ],
  meditate_evening: [
    i('Low lights, stereo headphones, a comfortable position: the "Deep Relaxation" session for 5 minutes. Relax your shoulders and jaw and let go of the day one breath at a time.', 'Sounds › Deep Relaxation (5 minutes)', sounds('stress', '5')),
    i('Seated or lying comfortably: the "Restorative Sleep" session for 5 minutes. Then switch off the screen and go to rest.', 'Sounds › Restorative Sleep (5 minutes)', sounds('sonno', '5')),
    i('To end the day with a quiet mind: the "Mental Balance" session for 5 minutes, with attention on your breath and on three things you are grateful for today.', 'Sounds › Mental Balance (5 minutes)', sounds('equilibrio_mentale', '5')),
  ],
  sport: [
    i('Walk briskly using two poles (even a simplified version): it works your whole body with little impact on the joints.', 'Nordic walking'),
    i('Skip with a rope for a few 1-minute sets with breaks: quick, effective and doable at home.'),
    i('Slow, flowing movements with the breath: great for balance and calm. Look for a 15-minute beginners\' video.', 'Tai chi'),
    i('Put on a playlist and dance freely for 15 minutes: it\'s a workout, but it feels like play.'),
    i('A bike ride at a comfortable pace, even just around the neighbourhood.'),
    i('Try a short session of dynamic stretching by following a beginners\' video.'),
    i('A free trial class in something that has always intrigued you: indoor climbing, swimming, dance.'),
  ],
  yoga: [
    i('Free lessons for every level: look for a 10-minute beginners\' session and follow along without thinking about anything else.', 'YouTube channel "Yoga With Adriene"'),
    i('A mini-sequence you can do without a video: cat-cow for 1 minute, downward dog for 1 minute, child\'s pose for 2 minutes, standing forward fold for 1 minute. Breathe slowly in each pose.'),
    i('If you have little space: sit cross-legged, lengthen your spine and do slow twists to the right and left, 5 breaths each side, then fold forward.'),
  ],
  recipe: [
    i('Chickpeas (tinned is fine, well rinsed) warmed with a drizzle of oil, rosemary and a little vegetable stock. Ready in 20 minutes.'),
    i('Quinoa cooked with seasonal vegetables, a drizzle of oil and lemon juice. Prepare it ahead and take it to the office.'),
    i('Oven-baked omelette with courgette and onion: few ingredients, easy, nourishing.'),
    i('Homemade hummus (chickpeas, tahini, lemon, garlic, oil) to eat with vegetable sticks.'),
    i('Overnight oats: rolled oats, yoghurt and fruit the evening before, breakfast ready in the morning.'),
    i('Oven-baked oily fish (mackerel, sardines) with diced vegetables and a drizzle of oil: quick and rich in good fats.'),
    i('Pumpkin and ginger soup: diced pumpkin cooked in stock with a piece of fresh ginger, blended.'),
    i('Wholewheat pasta with fresh cherry tomatoes, basil and a spoonful of raw olive oil: simple, filling, light.'),
  ],
  veg: [
    i('Raw fennel in thin slices with orange and a drizzle of oil: fresh and crunchy.'),
    i('Cavolo nero (black kale) sautéed in a pan with garlic and a splash of water: ready in 10 minutes.'),
    i('Oven-roasted broccoli with oil and lemon: it turns crisp and sweet.'),
    i('Oven-roasted cauliflower with a pinch of turmeric and pepper.'),
    i('Swiss chard sautéed with garlic and oil: a classic, inexpensive and rich in nutrients.'),
    i('Roasted pumpkin wedges with rosemary: sweet and filling.'),
    i('Red chicory seared in a pan or on the grill: slightly bitter and interesting.'),
  ],
  meal: [
    i('The plate method: half the plate vegetables, a quarter protein (pulses, fish, eggs, white meat), a quarter wholegrains, and a drizzle of raw olive oil.'),
    i('Quick lunch: tinned pulses (rinsed), cherry tomatoes, cucumber, a spoonful of oil and lemon. Ready in 5 minutes.'),
    i('Simple dinner: scrambled eggs with spinach and a slice of wholemeal bread.'),
    i('Oven-baked fish with thinly sliced potatoes and courgettes: one tray, little washing up.'),
    i('A complete big salad: leafy greens, a grain (spelt, brown rice), a protein and a handful of seeds.'),
  ],
  antiox: [
    i('Berries (blueberries, raspberries, blackberries), fresh or frozen: add them to yoghurt or breakfast.'),
    i('Spinach and dark leafy greens, raw in a salad or sautéed.'),
    i('Pomegranate: the seeds can be added to salads and yoghurt.'),
    i('Tomatoes, especially cooked, with a drizzle of oil.'),
    i('A handful of walnuts: rich in good fats and polyphenols.'),
    i('A small square of dark chocolate (at least 70–85% cocoa), eaten slowly.'),
  ],
  face_massage: [
    i('With clean fingers and dry hands: start from the centre of your forehead towards your temples with small, slow circles, 30 seconds.'),
    i('Then from the sides of your nose towards your cheekbones and out to your ears, 30 seconds, with light pressure.'),
    i('Finally from your chin along your jaw towards your ears, 30 seconds. Finish with three slow breaths and warm hands on your face.'),
  ],
  nature: [
    i('Get to the nearest park and sit under a tree for 10 minutes, with no phone in your hand.'),
    i('Walk slowly noticing 5 natural things you don\'t usually see: a leaf, the sky, the sound of a bird, a plant, the light.'),
    i('A botanical garden, a riverside path or a nearby hill: even half an hour changes your mood.'),
    i('The Japanese practice of forest bathing is simply walking slowly among trees, breathing and looking around.', 'Shinrin-yoku ("forest bathing")'),
    i('If you rarely get out: open the window, look at the sky and listen to the sounds for 5 minutes; or tend a plant on the balcony.'),
  ],
};

export const CURATED_EN: CuratedPools = {
  energia: [
    { passage: 'Natural light in the first minutes after waking is the strongest signal for your body: it does more than any coffee to set your energy for the day.', pointer: 'Podcast "Huberman Lab" by Andrew Huberman' },
    { passage: 'Energy is not a fixed amount that runs out: it is more like a rhythm. Small regular breaks sustain it better than continuous effort with no stops.' },
  ],
  sonno: [
    { passage: 'Sleep is not lost time: it is when the body consolidates memory and repairs tissue. Sleeping well tonight is already an investment in how you\'ll feel tomorrow.', pointer: 'Book "Why We Sleep" by Matthew Walker' },
    { passage: 'Going to bed and waking up at the same time, even at weekends, helps your body more than any other sleep habit.' },
    { passage: 'A cool, dark room sends your brain the same signal as night: it\'s time to slow down.' },
  ],
  stress: [
    { passage: 'A pounding heart before a challenge is not a danger signal: it is your body preparing to do its best. Seeing it that way really changes its effect.', pointer: 'TED Talk "How to Make Stress Your Friend" by Kelly McGonigal' },
    { passage: 'If something makes you tense, it is often because it really matters to you. Stress, seen this way, is also a compass.' },
  ],
  movimento: [
    { passage: 'You don\'t need a perfect workout: a walk at a pace where you can still talk, done consistently, counts for more than an intense but occasional effort.', pointer: 'Podcast "The Drive" by Peter Attia' },
    { passage: 'The body is made to move a little at a time through the day, not just for one hour at the gym: getting up now and then matters more than you think.' },
  ],
  alimentazione: [
    { passage: 'There is no single miracle food: the variety of what you eat, week after week, matters more than today\'s single choice.' },
    { passage: 'Eating calmly, without distractions, changes how the body recognises hunger and fullness: not just what you eat, but how.' },
  ],
  pelle: [
    { passage: 'Your skin reflects your whole body: sleep, stress and nutrition matter enormously. Caring for it is caring for you as a whole.' },
    { passage: 'Drinking enough and protecting yourself from the sun remain, of all habits, the ones with the longest-lasting effect on skin over time.' },
  ],
  equilibrio_mentale: [
    { passage: 'You don\'t need to find more time: just bring full attention to something you already do today, like drinking a coffee without thinking about anything else.', pointer: 'Book "Wherever You Go, There You Are" by Jon Kabat-Zinn' },
    { passage: 'Mindfulness is not emptying the mind: it is noticing what is happening in this moment, without having to judge or change it right away.' },
    { passage: 'Even a single minute focused on your breath is already a complete practice, not a preview of something longer.' },
  ],
};
