import { idea as i, sounds, IdeaPools, CuratedPools } from './shared';

// Español: ideas para las tareas «leer / escuchar / probar». Referencias culturales elegidas para quien habla español.
export const IDEAS_ES: IdeaPools = {
  read_inspire: [
    i('No hace falta sentirse listo/a para empezar: uno se vuelve listo/a haciendo. Hoy elige un solo gesto pequeño y hazlo ahora, antes de decidir si te apetece.'),
    i('Los días difíciles no borran los avances: son el terreno donde los hábitos echan raíces. Estar aquí hoy, aunque estés cansado/a, vale más que un día perfecto.'),
    i('Lo que te pesa suele tener que ver con lo que te importa. Prueba a preguntarte no «¿por qué estoy bajo presión?», sino «¿qué intento proteger?».'),
    i('Cuidarse no es egoísmo: es lo que te permite tener más que dar a los demás. Cinco minutos para ti no se los quitas a nadie.'),
    i('Cartas breves, escritas con calidez, sobre el valor de vivir las propias preguntas sin tener enseguida las respuestas. Lee aunque sea una.', 'Libro «Cartas a un joven poeta» de Rainer Maria Rilke'),
    i('Pensamientos brevísimos de un emperador que escribía para mantener el equilibrio. Abre una página al azar y lee el primer pensamiento.', 'Libro «Meditaciones» de Marco Aurelio'),
    i('Un texto breve y claro sobre cómo aprovechar bien el tiempo. Bastan unas pocas páginas para cambiar la perspectiva sobre el día.', 'Libro «De la brevedad de la vida» de Séneca'),
    i('Sobre cómo recuperar la serenidad deteniéndote en el momento presente, en lugar de aplazarlo todo hasta que todo esté en orden.', 'Libro «El poder del ahora» de Eckhart Tolle'),
    i('Sobre el valor de mostrarse imperfecto/a. Cualquier capítulo basta para sentirse menos solo/a con los propios defectos.', 'Libro «Los dones de la imperfección» de Brené Brown'),
  ],
  podcast: [
    i('Psicología cotidiana contada con claridad y cercanía, para entender mejor cómo funciona la mente.', 'Pódcast «Entiende Tu Mente» de Molo Cebrián'),
    i('La ciencia de la felicidad explicada por una profesora de Yale: episodios prácticos con pequeños hábitos para probar enseguida. En inglés.', 'Pódcast «The Happiness Lab» de Laurie Santos'),
    i('Meditación y vida cotidiana contadas con humor y sinceridad, ideal para empezar de cero. En inglés.', 'Pódcast «Ten Percent Happier» con Dan Harris'),
    i('Por qué hacemos lo que hacemos: psicología y neurociencia contadas como historias. En inglés.', 'Pódcast «Hidden Brain» de Shankar Vedantam'),
    i('Neurociencia aplicada al sueño, la energía y la concentración. Los episodios son largos: escucha aunque sean solo los primeros 10 minutos. En inglés.', 'Pódcast «Huberman Lab» de Andrew Huberman'),
    i('Un médico que habla de pequeños hábitos diarios para sentirse mejor, sin extremos. En inglés.', 'Pódcast «Feel Better, Live More» del Dr. Rangan Chatterjee'),
    i('Conversaciones lentas y profundas sobre el sentido de las cosas, para cuando te apetezca detenerte. En inglés.', 'Pódcast «On Being» con Krista Tippett'),
  ],
  read_relax: [
    i('Páginas breves y fluidas, perfectas para desconectar: con 10 notarás que la mente va más despacio.', 'Libro «El principito» de Antoine de Saint-Exupéry'),
    i('Relatos breves y ligeros: uno cada noche, sin compromiso y sin prisa por terminar.', 'Libro «Marcovaldo o las estaciones en la ciudad» de Italo Calvino'),
    i('Un libro corto de ritmo lento y tranquilo, que acompaña hacia el sueño.', 'Libro «El viejo y el mar» de Ernest Hemingway'),
    i('Prosa sencilla y pausada, adecuada para cerrar el día.', 'Libro «Siddhartha» de Hermann Hesse'),
    i('Capítulos brevísimos y un ritmo suave: se lee a sorbitos.', 'Libro «Seda» de Alessandro Baricco'),
    i('Un cuento amable y esperanzador, que se lee unas páginas cada vez.', 'Libro «El alquimista» de Paulo Coelho'),
    i('Releer un libro que ya amaste relaja más que descubrir uno nuevo: elige uno de tus favoritos y lee solo 10 páginas.'),
    i('Si no tienes un libro a mano, una colección de cuentos breves o de poemas es lo ideal: puedes parar en cualquier página sin perder el hilo.'),
  ],
  tisana: [
    i('La clásica de la noche: caliente, sin azúcar, bebida despacio y sin pantallas.', 'Manzanilla'),
    i('De aroma a limón, delicada, estupenda después de cenar.', 'Melisa'),
    i('Suave y dulce de forma natural, perfecta para ir más despacio antes de acostarte.', 'Tila'),
    i('Un aroma que invita a relajarse, también mezclada con manzanilla.', 'Lavanda'),
    i('Si la digestión va un poco lenta, ayuda a terminar la noche con calma.', 'Hinojo'),
    i('El ritual cuenta tanto como la hierba: prepara la infusión sin prisa, sostén la taza entre las manos y bébela sentado/a, sin el móvil.'),
  ],
  music_relax: [
    i('En la sección Sonidos encuentras la sesión «Relajación profunda», ondas alfa a 10 Hz pensadas para la relajación. Ponte cómodo/a con auriculares estéreo, configura 10 minutos y pulsa Play.', 'Sonidos › Relajación profunda', sounds('stress')),
    i('Para una pausa más meditativa: la sesión «Equilibrio mental», ondas theta a 6 Hz. Auriculares estéreo, ojos cerrados, 10 minutos.', 'Sonidos › Equilibrio mental', sounds('equilibrio_mentale')),
    i('La sesión «Regeneración celular», ondas theta a 4 Hz, para una pausa lenta y profunda. Auriculares estéreo y 10 minutos sin hacer nada más.', 'Sonidos › Regeneración celular', sounds('pelle')),
  ],
  hobby: [
    i('Colorea un mandala o haz garabatos libres: no hace falta saber dibujar, solo dejar ir la mano.'),
    i('Cuida una planta: quítale el polvo a las hojas, riégala, obsérvala de cerca.'),
    i('Un puzle o un crucigrama: la mente se concentra en una tarea sencilla y deja ir los pensamientos.'),
    i('Toca o canta una pieza que conozcas, aunque sea bajito: la voz libera tensiones más de lo que parece.'),
    i('Escribe unas líneas a mano a una persona que te importe, aunque sea solo una tarjeta.'),
    i('Fotografía con el móvil tres cosas bonitas que encuentres a tu alrededor ahora mismo.'),
    i('Cocina algo solo por placer, aunque sea pequeño: una masa, un postre sencillo, una infusión especial.'),
  ],
  laugh: [
    i('Sketches brevísimos, sin palabras, que hacen reír en cualquier idioma: bastan 5 minutos en YouTube.', 'Mr. Bean (sketches en YouTube)'),
    i('Una comedia popular y divertidísima sobre choques culturales y familiares, para reír a gusto.', 'Película «Ocho apellidos vascos» (2014)'),
    i('Un clásico del humor del cine español, tierno y lleno de ironía.', 'Película «¡Bienvenido, Mister Marshall!» (1953)'),
    i('Comicidad muda y genial, tierna y divertida: incluso una sola escena cambia el ánimo.', 'Película «Tiempos modernos» de Charlie Chaplin'),
    i('El humor absurdo de los Monty Python, un clásico que nunca envejece.', 'Película «La vida de Brian» (1979)'),
    i('Llama o escribe a la persona que más te hace reír: incluso 5 minutos de chistes valen como una película.'),
  ],
  music_energy: [
    i('En la sección Sonidos encuentras la sesión «Energía y concentración», ondas beta a 20 Hz pensadas para la energía y la concentración. Auriculares estéreo, 10 minutos, Play.', 'Sonidos › Energía y concentración', sounds('energia')),
    i('Si quieres un empujón para moverte: la sesión «Motivación activa», ondas beta a 18 Hz. Auriculares estéreo y 10 minutos.', 'Sonidos › Motivación activa', sounds('movimento')),
  ],
  snack: [
    i('Fruta fresca y un pequeño puñado de almendras o nueces: azúcares y grasas buenas juntos, para una energía más estable.'),
    i('Un yogur griego natural con unos trozos de fruta.'),
    i('Palitos de zanahoria o de apio con un poco de hummus: crujiente y saciante.'),
    i('Garbanzos tostados al horno con un chorrito de aceite y especias: una versión sana del snack salado.'),
    i('Una manzana en rodajas con unas nueces, fácil de llevar en el bolso.'),
    i('Un plátano con una cucharadita de crema de cacahuete (solo cacahuetes, sin azúcares añadidos).'),
    i('Frutos secos sin sal en un tarrito: la porción justa es un puñado.'),
  ],
  meditate_morning: [
    i('Siéntate cómodo/a, con la espalda recta y auriculares estéreo. Inicia la sesión «Equilibrio mental» durante 5 minutos: lleva la atención a la respiración y, cada vez que la mente se distraiga, vuelve a ella con suavidad.', 'Sonidos › Equilibrio mental (5 minutos)', sounds('equilibrio_mentale', '5')),
    i('Para empezar el día con calma: la sesión «Relajación profunda» durante 5 minutos. Ojos cerrados, cuenta diez respiraciones lentas y empieza de nuevo desde uno cuando pierdas la cuenta.', 'Sonidos › Relajación profunda (5 minutos)', sounds('stress', '5')),
    i('Para empezar concentrado/a: la sesión «Energía y concentración» durante 5 minutos, sentado/a, con la atención en la respiración y en un solo objetivo del día.', 'Sonidos › Energía y concentración (5 minutos)', sounds('energia', '5')),
  ],
  meditate_evening: [
    i('Luces bajas, auriculares estéreo, postura cómoda: la sesión «Relajación profunda» durante 5 minutos. Relaja los hombros y la mandíbula y deja ir el día respiración a respiración.', 'Sonidos › Relajación profunda (5 minutos)', sounds('stress', '5')),
    i('Sentado/a o tumbado/a con comodidad: la sesión «Sueño reparador» durante 5 minutos. Después apaga la pantalla y ve a descansar.', 'Sonidos › Sueño reparador (5 minutos)', sounds('sonno', '5')),
    i('Para cerrar el día con la mente quieta: la sesión «Equilibrio mental» durante 5 minutos, con la atención en la respiración y en tres cosas por las que estás agradecido/a hoy.', 'Sonidos › Equilibrio mental (5 minutos)', sounds('equilibrio_mentale', '5')),
  ],
  sport: [
    i('Camina a paso ligero usando dos bastones (incluso una versión simplificada): trabaja todo el cuerpo con poco impacto en las articulaciones.', 'Marcha nórdica'),
    i('Salta a la comba unas series de 1 minuto con pausas: rápido, eficaz y se puede hacer en casa.'),
    i('Movimientos lentos y fluidos, con la respiración: ideal para el equilibrio y la calma. Busca un vídeo para principiantes de 15 minutos.', 'Tai chi'),
    i('Pon una lista de reproducción y baila libremente durante 15 minutos: es entrenamiento, pero parece un juego.'),
    i('Un paseo en bici a ritmo cómodo, aunque sea solo por el barrio.'),
    i('Prueba una breve sesión de estiramientos dinámicos siguiendo un vídeo para principiantes.'),
    i('Una clase de prueba gratuita de algo que siempre te ha intrigado: escalada en rocódromo, natación, baile.'),
  ],
  yoga: [
    i('Clases gratuitas para todos los niveles: busca una sesión de 10 minutos para principiantes y síguela sin pensar en nada más. En inglés.', 'Canal de YouTube «Yoga With Adriene»'),
    i('Una mini secuencia que se puede hacer incluso sin vídeo: gato-vaca durante 1 minuto, perro boca abajo durante 1 minuto, postura del niño durante 2 minutos, flexión hacia delante de pie durante 1 minuto. Respira despacio en cada postura.'),
    i('Si tienes poco espacio: siéntate con las piernas cruzadas, alarga la espalda y haz torsiones lentas a derecha e izquierda, 5 respiraciones por lado, y luego inclínate hacia delante.'),
  ],
  recipe: [
    i('Garbanzos (de bote, bien enjuagados) calentados con un chorrito de aceite, romero y un poco de caldo de verduras. Listo en 20 minutos.'),
    i('Quinoa cocida con verduras de temporada, un chorrito de aceite y zumo de limón. Se prepara con antelación y se lleva a la oficina.'),
    i('Tortilla al horno con calabacín y cebolla: pocos ingredientes, fácil y nutritiva.'),
    i('Hummus casero (garbanzos, tahini, limón, ajo, aceite) para comer con palitos de verdura.'),
    i('Overnight oats: copos de avena, yogur y fruta la noche anterior, desayuno listo por la mañana.'),
    i('Pescado azul al horno (caballa, sardinas) con verduras en dados y un chorrito de aceite: rápido y rico en grasas buenas.'),
    i('Crema de calabaza y jengibre: calabaza en dados cocida con caldo y un trozo de jengibre fresco, triturada.'),
    i('Pasta integral con tomates cherry frescos, albahaca y una cucharada de aceite de oliva en crudo: sencilla, saciante, ligera.'),
  ],
  veg: [
    i('Hinojo crudo en láminas finas con naranja y un chorrito de aceite: fresco y crujiente.'),
    i('Col rizada (kale) salteada en la sartén con ajo y un chorrito de agua: lista en 10 minutos.'),
    i('Brócoli al horno con aceite y limón: se vuelve crujiente y dulce.'),
    i('Coliflor al horno con una pizca de cúrcuma y pimienta.'),
    i('Acelgas salteadas con ajo y aceite: clásicas, económicas y ricas en nutrientes.'),
    i('Calabaza asada en gajos con romero: dulce y saciante.'),
    i('Achicoria roja (radicchio) pasada por la sartén o a la parrilla: ligeramente amarga e interesante.'),
  ],
  meal: [
    i('El método del plato: la mitad del plato de verduras, un cuarto de proteínas (legumbres, pescado, huevos, carne blanca), un cuarto de cereales integrales y un chorrito de aceite de oliva en crudo.'),
    i('Comida rápida: legumbres de bote enjuagadas, tomates cherry, pepino, una cucharada de aceite y limón. Lista en 5 minutos.'),
    i('Cena sencilla: huevos revueltos con espinacas y una rebanada de pan integral.'),
    i('Pescado al horno con patatas y calabacines cortados finos: una sola bandeja, poco que fregar.'),
    i('Una ensalada completa: verduras de hoja, un cereal (espelta, arroz integral), una proteína y un puñado de semillas.'),
  ],
  antiox: [
    i('Frutos rojos (arándanos, frambuesas, moras), frescos o congelados: añádelos al yogur o al desayuno.'),
    i('Espinacas y verduras de hoja oscura, crudas en ensalada o salteadas.'),
    i('Granada: los granos se añaden a ensaladas y yogures.'),
    i('Tomates, sobre todo cocinados, con un chorrito de aceite.'),
    i('Un puñado de nueces: ricas en grasas buenas y polifenoles.'),
    i('Un cuadradito de chocolate negro (al menos 70-85 % de cacao), comido despacio.'),
  ],
  face_massage: [
    i('Con los dedos limpios y las manos secas: empieza desde el centro de la frente hacia las sienes con pequeños círculos lentos, 30 segundos.'),
    i('Después desde los lados de la nariz hacia los pómulos y hasta las orejas, 30 segundos, con presión suave.'),
    i('Por último desde la barbilla a lo largo de la mandíbula hacia las orejas, 30 segundos. Termina con tres respiraciones lentas y las manos calientes sobre el rostro.'),
  ],
  nature: [
    i('Ve al parque más cercano y siéntate 10 minutos bajo un árbol, sin el móvil en la mano.'),
    i('Camina despacio fijándote en 5 elementos naturales en los que no sueles reparar: una hoja, el cielo, el sonido de un pájaro, una planta, la luz.'),
    i('Un jardín botánico, un paseo junto al río o una colina cercana: incluso media hora cambia el ánimo.'),
    i('La práctica japonesa del baño de bosque consiste simplemente en caminar despacio entre los árboles, respirando y mirando a tu alrededor.', 'Shinrin-yoku («baño de bosque»)'),
    i('Si sales poco: abre la ventana, mira el cielo y escucha los sonidos durante 5 minutos; o cuida una planta en el balcón.'),
  ],
};

export const CURATED_ES: CuratedPools = {
  energia: [
    { passage: 'La luz natural de los primeros minutos tras despertarte es la señal más fuerte para tu cuerpo: vale más que cualquier café para ajustar la energía del día.', pointer: 'Pódcast «Huberman Lab» de Andrew Huberman' },
    { passage: 'La energía no es una cantidad fija que se agota: se parece más a un ritmo. Pequeñas pausas regulares la mantienen mejor que un esfuerzo continuo sin paradas.' },
  ],
  sonno: [
    { passage: 'El sueño no es tiempo perdido: es el momento en que el cuerpo consolida la memoria y repara los tejidos. Dormir bien esta noche ya es una inversión en cómo estarás mañana.', pointer: 'Libro «Por qué dormimos» de Matthew Walker' },
    { passage: 'Acostarte y despertarte siempre a la misma hora, también el fin de semana, ayuda al cuerpo más que cualquier otro hábito relacionado con el sueño.' },
    { passage: 'Una habitación fresca y oscura envía al cerebro la misma señal que la noche: es hora de ir más despacio.' },
  ],
  stress: [
    { passage: 'Un corazón que late fuerte antes de un reto no es una señal de peligro: es el cuerpo que se prepara para dar lo mejor. Verlo así cambia de verdad su efecto.', pointer: 'Charla TED «How to Make Stress Your Friend» de Kelly McGonigal' },
    { passage: 'Si algo te genera tensión, suele ser porque de verdad te importa. El estrés, visto así, también es una brújula.' },
  ],
  movimento: [
    { passage: 'No hace falta un entrenamiento perfecto: una caminata a un ritmo en el que todavía puedes hablar, hecha con constancia, cuenta más que un esfuerzo intenso pero esporádico.', pointer: 'Pódcast «The Drive» de Peter Attia' },
    { passage: 'El cuerpo está hecho para moverse un poco cada vez a lo largo del día, no solo durante una hora en el gimnasio: levantarte de vez en cuando cuenta más de lo que piensas.' },
  ],
  alimentazione: [
    { passage: 'No existe un único alimento milagroso: la variedad de lo que comes, semana tras semana, cuenta más que la elección de hoy.' },
    { passage: 'Comer con calma, sin distracciones, cambia la forma en que el cuerpo reconoce el hambre y la saciedad: no solo qué comes, sino cómo.' },
  ],
  pelle: [
    { passage: 'La piel refleja todo el cuerpo: el sueño, el estrés y la alimentación importan muchísimo. Cuidarla es cuidarte en conjunto.' },
    { passage: 'Beber lo suficiente y protegerte del sol siguen siendo, de todos los hábitos, los que tienen el efecto más duradero en la piel con el tiempo.' },
  ],
  equilibrio_mentale: [
    { passage: 'No hace falta encontrar más tiempo: basta con poner plena atención en algo que ya haces hoy, como tomarte un café sin pensar en nada más.', pointer: 'Libro «Wherever You Go, There You Are» de Jon Kabat-Zinn' },
    { passage: 'La atención plena no es vaciar la mente: es notar lo que ocurre en este momento, sin tener que juzgarlo ni cambiarlo enseguida.' },
    { passage: 'Incluso un solo minuto concentrado en la respiración ya es una práctica completa, no la antesala de algo más largo.' },
  ],
};
