import { idea as i, sounds, IdeaPools, CuratedPools } from './shared';

// Français : idées pour les tâches « lire / écouter / essayer ». Références culturelles choisies pour un public francophone.
export const IDEAS_FR: IdeaPools = {
  read_inspire: [
    i('Pas besoin de te sentir prêt(e) pour commencer : on devient prêt(e) en faisant. Aujourd’hui, choisis un tout petit geste et fais-le maintenant, avant de décider si tu en as envie.'),
    i('Les journées difficiles n’effacent pas les progrès : c’est le terreau où les habitudes prennent racine. Être ici aujourd’hui, même fatigué(e), vaut plus qu’une journée parfaite.'),
    i('Ce qui te pèse a souvent un lien avec ce qui compte pour toi. Essaie de te demander non pas « pourquoi suis-je sous pression ? », mais « qu’est-ce que j’essaie de protéger ? ».'),
    i('Prendre soin de soi n’est pas de l’égoïsme : c’est ce qui te permet d’avoir plus à donner aux autres. Cinq minutes pour toi ne sont retirées à personne.'),
    i('De courtes lettres, écrites avec chaleur, sur le courage de vivre ses questions sans avoir tout de suite les réponses. Lis-en ne serait-ce qu’une.', 'Livre « Lettres à un jeune poète » de Rainer Maria Rilke'),
    i('De très courtes pensées d’un empereur qui écrivait pour garder son équilibre. Ouvre une page au hasard et lis la première pensée.', 'Livre « Pensées pour moi-même » de Marc Aurèle'),
    i('Un texte court et limpide sur la façon de bien utiliser son temps. Quelques pages suffisent pour changer ta perspective sur la journée.', 'Livre « De la brièveté de la vie » de Sénèque'),
    i('Sur la façon de retrouver la sérénité en s’arrêtant dans le moment présent, au lieu de tout remettre à quand tout ira bien.', 'Livre « Le Pouvoir du moment présent » d’Eckhart Tolle'),
    i('Sur le courage de se montrer imparfait(e). N’importe quel chapitre suffit pour se sentir moins seul(e) avec ses défauts.', 'Livre « Les Dons de l’imperfection » de Brené Brown'),
  ],
  podcast: [
    i('Des conversations pour mieux vivre au quotidien : psychologie, relations, petites habitudes à essayer tout de suite.', 'Podcast « Change ma vie » de Clotilde Dusoulier'),
    i('Un grand rendez-vous de réflexion sur le sens des choses, quand tu as envie de t’arrêter un moment.', 'Émission « Les Chemins de la philosophie » (France Culture)'),
    i('La science du bonheur expliquée par une professeure de Yale : des épisodes pratiques. En anglais.', 'Podcast « The Happiness Lab » de Laurie Santos'),
    i('La méditation et la vie quotidienne racontées avec humour et honnêteté, idéal pour partir de zéro. En anglais.', 'Podcast « Ten Percent Happier » avec Dan Harris'),
    i('Pourquoi nous agissons comme nous agissons : psychologie et neurosciences racontées comme des histoires. En anglais.', 'Podcast « Hidden Brain » de Shankar Vedantam'),
    i('Les neurosciences appliquées au sommeil, à l’énergie et à la concentration. Les épisodes sont longs : écoute juste les 10 premières minutes. En anglais.', 'Podcast « Huberman Lab » d’Andrew Huberman'),
    i('Un médecin qui parle de petites habitudes quotidiennes pour se sentir mieux, sans extrêmes. En anglais.', 'Podcast « Feel Better, Live More » du Dr Rangan Chatterjee'),
  ],
  read_relax: [
    i('Des pages courtes et fluides, parfaites pour décrocher : 10 suffisent pour sentir l’esprit ralentir.', 'Livre « Le Petit Prince » d’Antoine de Saint-Exupéry'),
    i('Des récits brefs et légers : un par soir, sans pression ni envie de finir.', 'Livre « Marcovaldo ou Les Saisons en ville » d’Italo Calvino'),
    i('Un livre court au rythme lent et paisible, qui accompagne vers le sommeil.', 'Livre « Le Vieil Homme et la Mer » d’Ernest Hemingway'),
    i('Une prose simple et posée, adaptée pour clore la journée.', 'Livre « Siddhartha » de Hermann Hesse'),
    i('Des chapitres très courts et un rythme doux : on lit par petites gorgées.', 'Livre « Soie » d’Alessandro Baricco'),
    i('Un conte doux et plein d’espoir, qui se lit quelques pages à la fois.', 'Livre « L’Alchimiste » de Paulo Coelho'),
    i('Relire un livre que tu as déjà aimé détend plus que d’en découvrir un nouveau : choisis l’un de tes préférés et lis seulement 10 pages.'),
    i('Si tu n’as pas de livre sous la main, un recueil de nouvelles ou de poèmes est idéal : tu peux t’arrêter à n’importe quelle page sans perdre le fil.'),
  ],
  tisana: [
    i('La classique du soir : chaude, sans sucre, bue lentement sans écrans.', 'Camomille'),
    i('Au parfum de citron, délicate, excellente après le dîner.', 'Mélisse'),
    i('Douce et naturellement sucrée, parfaite pour ralentir avant de te coucher.', 'Tilleul'),
    i('Un parfum qui invite à se détendre, aussi en mélange avec la camomille.', 'Lavande'),
    i('Si la digestion est un peu lente, elle aide à terminer la soirée en douceur.', 'Fenouil'),
    i('Le rituel compte autant que la plante : prépare ta tisane sans te presser, garde la tasse entre tes mains et bois-la assis(e), sans téléphone.'),
  ],
  music_relax: [
    i('Dans la section Sons, tu trouves la séance « Relaxation profonde », des ondes alpha à 10 Hz conçues pour la détente. Installe-toi confortablement avec un casque stéréo, règle 10 minutes et appuie sur Play.', 'Sons › Relaxation profonde', sounds('stress')),
    i('Pour une pause plus méditative : la séance « Équilibre mental », des ondes thêta à 6 Hz. Casque stéréo, yeux fermés, 10 minutes.', 'Sons › Équilibre mental', sounds('equilibrio_mentale')),
    i('La séance « Régénération cellulaire », des ondes thêta à 4 Hz, pour une pause lente et profonde. Casque stéréo et 10 minutes sans rien faire d’autre.', 'Sons › Régénération cellulaire', sounds('pelle')),
  ],
  hobby: [
    i('Colorie un mandala ou fais des gribouillis libres : pas besoin de savoir dessiner, il suffit de laisser aller la main.'),
    i('Occupe-toi d’une plante : dépoussière ses feuilles, arrose-la, observe-la de près.'),
    i('Un puzzle ou des mots croisés : l’esprit se concentre sur une tâche simple et laisse partir les pensées.'),
    i('Joue ou chante un morceau que tu connais, même tout doucement : la voix libère les tensions plus qu’on ne le croit.'),
    i('Écris quelques lignes à la main à une personne qui compte pour toi, ne serait-ce qu’une carte.'),
    i('Photographie avec ton téléphone trois belles choses autour de toi, maintenant.'),
    i('Cuisine quelque chose juste pour le plaisir, même une petite chose : une pâte, un dessert simple, une tisane spéciale.'),
  ],
  laugh: [
    i('Des sketchs très courts, sans paroles, qui font rire dans toutes les langues : 5 minutes sur YouTube suffisent.', 'Mr. Bean (sketchs sur YouTube)'),
    i('Une comédie culte, pleine de répliques qui font mouche, pour rire de bon cœur.', 'Film « Le Dîner de cons » (1998)'),
    i('Une comédie populaire et chaleureuse sur une bande d’amis en vacances.', 'Film « Les Bronzés » (1978)'),
    i('Une comédie d’aventures irrésistible, un grand classique du rire en famille.', 'Film « La Grande Vadrouille » (1966)'),
    i('Une comédie tendre et drôle, pour sourire et se laisser attendrir.', 'Film « Intouchables » (2011)'),
    i('Appelle ou écris à la personne qui te fait le plus rire : même 5 minutes de blagues valent un film.'),
  ],
  music_energy: [
    i('Dans la section Sons, tu trouves la séance « Énergie et focus », des ondes bêta à 20 Hz conçues pour l’énergie et la concentration. Casque stéréo, 10 minutes, Play.', 'Sons › Énergie et focus', sounds('energia')),
    i('Si tu veux un coup de pouce pour bouger : la séance « Motivation active », des ondes bêta à 18 Hz. Casque stéréo et 10 minutes.', 'Sons › Motivation active', sounds('movimento')),
  ],
  snack: [
    i('Des fruits frais et une petite poignée d’amandes ou de noix : sucres et bons gras ensemble, pour une énergie plus stable.'),
    i('Un petit pot de yaourt grec nature avec quelques morceaux de fruit.'),
    i('Des bâtonnets de carotte ou de céleri avec un peu de houmous : croquant et rassasiant.'),
    i('Des pois chiches rôtis au four avec un filet d’huile et des épices : une version saine du snack salé.'),
    i('Une pomme en tranches avec quelques noix, facile à emporter dans le sac.'),
    i('Une banane avec une cuillère à café de beurre de cacahuète (uniquement des cacahuètes, sans sucres ajoutés).'),
    i('Des fruits secs non salés dans une petite boîte : la bonne portion, c’est une poignée.'),
  ],
  meditate_morning: [
    i('Assieds-toi confortablement, le dos droit et un casque stéréo. Lance la séance « Équilibre mental » pendant 5 minutes : porte ton attention sur ta respiration et, chaque fois que l’esprit s’égare, reviens-y avec douceur.', 'Sons › Équilibre mental (5 minutes)', sounds('equilibrio_mentale', '5')),
    i('Pour commencer la journée dans le calme : la séance « Relaxation profonde » pendant 5 minutes. Yeux fermés, compte dix respirations lentes et recommence à un quand tu perds le fil.', 'Sons › Relaxation profonde (5 minutes)', sounds('stress', '5')),
    i('Pour démarrer concentré(e) : la séance « Énergie et focus » pendant 5 minutes, assis(e), l’attention sur la respiration et sur un seul objectif de la journée.', 'Sons › Énergie et focus (5 minutes)', sounds('energia', '5')),
  ],
  meditate_evening: [
    i('Lumières douces, casque stéréo, position confortable : la séance « Relaxation profonde » pendant 5 minutes. Relâche les épaules et la mâchoire et laisse partir la journée, une respiration à la fois.', 'Sons › Relaxation profonde (5 minutes)', sounds('stress', '5')),
    i('Assis(e) ou allongé(e) confortablement : la séance « Sommeil réparateur » pendant 5 minutes. Puis éteins l’écran et va te reposer.', 'Sons › Sommeil réparateur (5 minutes)', sounds('sonno', '5')),
    i('Pour finir la journée l’esprit calme : la séance « Équilibre mental » pendant 5 minutes, l’attention sur la respiration et sur trois choses dont tu es reconnaissant(e) aujourd’hui.', 'Sons › Équilibre mental (5 minutes)', sounds('equilibrio_mentale', '5')),
  ],
  sport: [
    i('Marche d’un pas vif avec deux bâtons (même une version simplifiée) : tout le corps travaille, avec peu d’impact sur les articulations.', 'Marche nordique'),
    i('Saute à la corde quelques séries d’1 minute avec des pauses : rapide, efficace et faisable à la maison.'),
    i('Des mouvements lents et fluides, avec la respiration : excellent pour l’équilibre et le calme. Cherche une vidéo pour débutants de 15 minutes.', 'Tai-chi'),
    i('Mets une playlist et danse librement pendant 15 minutes : c’est un entraînement, mais ça ressemble à un jeu.'),
    i('Une balade à vélo à un rythme confortable, même juste autour du quartier.'),
    i('Essaie une courte séance d’étirements dynamiques en suivant une vidéo pour débutants.'),
    i('Un cours d’essai gratuit d’une activité qui t’a toujours intrigué(e) : escalade en salle, natation, danse.'),
  ],
  yoga: [
    i('Des cours gratuits pour tous les niveaux : cherche une séance de 10 minutes pour débutants et suis-la sans penser à rien d’autre. En anglais.', 'Chaîne YouTube « Yoga With Adriene »'),
    i('Une mini-séquence à faire même sans vidéo : chat-vache pendant 1 minute, chien tête en bas pendant 1 minute, posture de l’enfant pendant 2 minutes, flexion avant debout pendant 1 minute. Respire lentement dans chaque posture.'),
    i('Si tu as peu de place : assieds-toi en tailleur, allonge le dos et fais de lentes torsions à droite et à gauche, 5 respirations de chaque côté, puis penche-toi en avant.'),
  ],
  recipe: [
    i('Des pois chiches (en boîte, bien rincés) réchauffés avec un filet d’huile, du romarin et un peu de bouillon de légumes. Prêt en 20 minutes.'),
    i('Du quinoa cuit avec des légumes de saison, un filet d’huile et du jus de citron. Se prépare à l’avance et se glisse dans la gamelle du bureau.'),
    i('Une omelette au four aux courgettes et à l’oignon : peu d’ingrédients, facile, nourrissante.'),
    i('Du houmous maison (pois chiches, tahini, citron, ail, huile) à manger avec des bâtonnets de légumes.'),
    i('Overnight oats : flocons d’avoine, yaourt et fruits la veille au soir, petit-déjeuner prêt au matin.'),
    i('Du poisson gras au four (maquereau, sardines) avec des légumes en dés et un filet d’huile : rapide et riche en bons gras.'),
    i('Velouté de potiron et gingembre : potiron en dés cuit dans du bouillon avec un morceau de gingembre frais, mixé.'),
    i('Des pâtes complètes avec des tomates cerises fraîches, du basilic et une cuillère d’huile d’olive crue : simple, rassasiant, léger.'),
  ],
  veg: [
    i('Du fenouil cru en fines lamelles avec de l’orange et un filet d’huile : frais et croquant.'),
    i('Du chou kale sauté à la poêle avec de l’ail et un peu d’eau : prêt en 10 minutes.'),
    i('Du brocoli au four avec de l’huile et du citron : il devient croustillant et doux.'),
    i('Du chou-fleur au four avec une pincée de curcuma et de poivre.'),
    i('Des blettes sautées à l’ail et à l’huile : un classique, économique et riche en nutriments.'),
    i('Du potiron rôti en quartiers avec du romarin : doux et rassasiant.'),
    i('De la chicorée rouge (trévise) saisie à la poêle ou au gril : légèrement amère et intéressante.'),
  ],
  meal: [
    i('La méthode de l’assiette : la moitié en légumes, un quart de protéines (légumineuses, poisson, œufs, viande blanche), un quart de céréales complètes, et un filet d’huile d’olive crue.'),
    i('Déjeuner rapide : légumineuses en boîte rincées, tomates cerises, concombre, une cuillère d’huile et du citron. Prêt en 5 minutes.'),
    i('Dîner simple : œufs brouillés aux épinards et une tranche de pain complet.'),
    i('Poisson au four avec des pommes de terre et des courgettes en fines tranches : un seul plat, peu de vaisselle.'),
    i('Une grande salade complète : légumes verts, une céréale (épeautre, riz complet), une protéine et une poignée de graines.'),
  ],
  antiox: [
    i('Des fruits rouges (myrtilles, framboises, mûres), frais ou surgelés : ajoute-les au yaourt ou au petit-déjeuner.'),
    i('Des épinards et des légumes à feuilles foncées, crus en salade ou sautés.'),
    i('La grenade : les grains s’ajoutent aux salades et aux yaourts.'),
    i('Des tomates, surtout cuites, avec un filet d’huile.'),
    i('Une poignée de noix : riches en bons gras et en polyphénols.'),
    i('Un carré de chocolat noir (au moins 70 à 85 % de cacao), mangé lentement.'),
  ],
  face_massage: [
    i('Avec des doigts propres et des mains sèches : pars du centre du front vers les tempes avec de petits cercles lents, 30 secondes.'),
    i('Puis des ailes du nez vers les pommettes et jusqu’aux oreilles, 30 secondes, avec une pression légère.'),
    i('Enfin du menton le long de la mâchoire vers les oreilles, 30 secondes. Termine par trois respirations lentes et les mains chaudes sur le visage.'),
  ],
  nature: [
    i('Rends-toi au parc le plus proche et assieds-toi 10 minutes sous un arbre, sans téléphone à la main.'),
    i('Marche lentement en observant 5 éléments naturels que tu ne remarques d’habitude pas : une feuille, le ciel, le chant d’un oiseau, une plante, la lumière.'),
    i('Un jardin botanique, un bord de rivière ou une colline proche : même une demi-heure change l’humeur.'),
    i('La pratique japonaise du bain de forêt consiste simplement à marcher doucement entre les arbres, en respirant et en regardant autour de soi.', 'Shinrin-yoku (« bain de forêt »)'),
    i('Si tu sors peu : ouvre la fenêtre, regarde le ciel et écoute les sons pendant 5 minutes ; ou occupe-toi d’une plante sur le balcon.'),
  ],
};

export const CURATED_FR: CuratedPools = {
  energia: [
    { passage: 'La lumière naturelle des premières minutes après le réveil est le signal le plus fort pour ton corps : elle vaut plus que n’importe quel café pour régler l’énergie de la journée.', pointer: 'Podcast « Huberman Lab » d’Andrew Huberman' },
    { passage: 'L’énergie n’est pas une quantité fixe qui s’épuise : elle ressemble plus à un rythme. De petites pauses régulières la maintiennent mieux qu’un effort continu sans arrêt.' },
  ],
  sonno: [
    { passage: 'Le sommeil n’est pas du temps perdu : c’est le moment où le corps consolide la mémoire et répare les tissus. Bien dormir cette nuit, c’est déjà investir dans ta forme de demain.', pointer: 'Livre « Pourquoi nous dormons » de Matthew Walker' },
    { passage: 'Se coucher et se réveiller toujours à la même heure, même le week-end, aide le corps plus que toute autre habitude liée au sommeil.' },
    { passage: 'Une chambre fraîche et sombre envoie au cerveau le même signal que la nuit : il est temps de ralentir.' },
  ],
  stress: [
    { passage: 'Un cœur qui bat fort avant un défi n’est pas un signal de danger : c’est le corps qui se prépare à donner le meilleur. Le voir ainsi en change vraiment l’effet.', pointer: 'Conférence TED « How to Make Stress Your Friend » de Kelly McGonigal' },
    { passage: 'Si quelque chose te crée de la tension, c’est souvent parce que cela compte vraiment pour toi. Le stress, vu ainsi, est aussi une boussole.' },
  ],
  movimento: [
    { passage: 'Pas besoin d’un entraînement parfait : une marche à un rythme où tu peux encore parler, faite avec régularité, compte plus qu’un effort intense mais occasionnel.', pointer: 'Podcast « The Drive » de Peter Attia' },
    { passage: 'Le corps est fait pour bouger un peu à la fois tout au long de la journée, pas seulement une heure à la salle de sport : se lever de temps en temps compte plus qu’on ne le pense.' },
  ],
  alimentazione: [
    { passage: 'Il n’existe pas d’aliment miraculeux : la variété de ce que tu manges, semaine après semaine, compte plus que le choix d’aujourd’hui.' },
    { passage: 'Manger calmement, sans distractions, change la façon dont le corps reconnaît la faim et la satiété : pas seulement ce que tu manges, mais comment.' },
  ],
  pelle: [
    { passage: 'La peau reflète tout le corps : le sommeil, le stress et l’alimentation comptent énormément. En prendre soin, c’est prendre soin de toi dans ton ensemble.' },
    { passage: 'Boire suffisamment et te protéger du soleil restent, parmi toutes les habitudes, celles qui ont l’effet le plus durable sur la peau au fil du temps.' },
  ],
  equilibrio_mentale: [
    { passage: 'Pas besoin de trouver plus de temps : il suffit de porter une pleine attention à quelque chose que tu fais déjà aujourd’hui, comme boire un café sans penser à autre chose.', pointer: 'Livre « Wherever You Go, There You Are » de Jon Kabat-Zinn' },
    { passage: 'La pleine conscience, ce n’est pas vider l’esprit : c’est remarquer ce qui se passe en ce moment, sans devoir le juger ou le changer tout de suite.' },
    { passage: 'Même une seule minute concentrée sur la respiration est déjà une pratique complète, pas l’avant-goût de quelque chose de plus long.' },
  ],
};
