// Testi italiani dei compiti: dati puri, senza dipendenze (cosi' le traduzioni si agganciano
// qui senza giri di import). Devono restare identici a quelli del backend
// (backend/server.py e backend/task_templates_level2.json): il test i18n lo verifica.

// Pool di 15 micro-azioni per area. Stesso identico testo del backend
// (backend/server.py) per restare sincronizzati tra modalita' Guest (locale) e
// modalita' registrata (server).
export const TASK_TEMPLATES: { [key: string]: string[] } = {
  energia: [
    "Fai 5 minuti di stretching al risveglio",
    "Bevi un bicchiere d'acqua appena sveglio",
    "Esci all'aria aperta per 10 minuti",
    "Fai una pausa di 5 minuti ogni 2 ore",
    "Mangia uno snack energetico a metà mattina",
    "Evita caffeina dopo le 15:00",
    "Fai 10 respiri profondi durante la giornata",
    "Prendi il sole per 15 minuti",
    "Ascolta musica energizzante per 10 minuti",
    "Fai una breve passeggiata dopo pranzo",
    "Fai una doccia rivitalizzante al mattino",
    "Apri le tende appena sveglio per la luce naturale",
    "Fai 2 minuti di jumping jack per svegliarti",
    "Prepara la colazione la sera prima per non correre",
    "Alzati e stiracchiati ogni ora di lavoro",
  ],
  sonno: [
    "Vai a letto alla stessa ora",
    "Spegni gli schermi 30 minuti prima di dormire",
    "Leggi 10 pagine di un libro rilassante",
    "Prepara la camera per la notte (buio, fresco)",
    "Fai un bagno caldo serale",
    "Evita pasti pesanti dopo le 20:00",
    "Pratica 5 minuti di meditazione serale",
    "Scrivi 3 cose positive della giornata",
    "Bevi una tisana rilassante",
    "Fai stretching leggero prima di dormire",
    "Metti il telefono in un'altra stanza la sera",
    "Fai una doccia tiepida prima di coricarti",
    "Scrivi la lista delle cose da fare domani per liberare la mente",
    "Riduci le luci in casa un'ora prima di dormire",
    "Evita alcol nella serata",
  ],
  stress: [
    "Pratica 2 minuti di respirazione profonda",
    "Scrivi i tuoi pensieri per 5 minuti",
    "Ascolta musica rilassante per 10 minuti",
    "Fai una pausa consapevole senza multitasking",
    "Esci per una camminata di 15 minuti",
    "Chiama un amico per 10 minuti",
    "Pratica la gratitudine: annota 3 cose positive",
    "Fai stretching per rilassare le tensioni",
    "Disconnettiti dai social per 1 ora",
    "Dedica 10 minuti a un hobby che ami",
    "Fai una lista delle priorità del giorno",
    "Prova la tecnica di respirazione 4-7-8",
    "Concediti 5 minuti di silenzio senza distrazioni",
    "Scrivi su carta un pensiero negativo per ridimensionarlo",
    "Fai una risata guardando qualcosa di divertente",
  ],
  movimento: [
    "Cammina per 10 minuti",
    "Fai 10 squat durante una pausa",
    "Prendi le scale invece dell'ascensore",
    "Fai stretching per 5 minuti",
    "Balla per 5 minuti su una canzone che ami",
    "Fai una passeggiata dopo cena",
    "Pratica yoga per 10 minuti",
    "Fai 5 minuti di esercizi a corpo libero",
    "Alzati e muoviti ogni ora",
    "Prova un nuovo sport per 15 minuti",
    "Fai 5000 passi oggi",
    "Parcheggia più lontano e cammina un po' di più",
    "Fai 10 minuti di camminata veloce",
    "Fai qualche piegamento durante la giornata",
    "Fai una sessione di bici o camminata all'aperto",
  ],
  alimentazione: [
    "Mangia una porzione di verdura a pranzo",
    "Bevi 8 bicchieri d'acqua, distribuiti dalla mattina alla sera",
    "Fai uno snack con frutta fresca e qualche mandorla o noce, per non far salire troppo la glicemia",
    "Prepara un pasto sano con ingredienti freschi",
    "Evita cibi processati oggi",
    "Mangia consapevolmente senza distrazioni",
    "Aggiungi alla colazione una fonte proteica sana (uova, yogurt greco, frutta secca o legumi)",
    "Riduci lo zucchero raffinato",
    "Prova una nuova ricetta salutare",
    "Mangia noci o semi come snack",
    "Fai la spesa con una lista per evitare acquisti impulsivi",
    "Mastica lentamente ad ogni pasto",
    "Sostituisci una bevanda zuccherata con acqua o tisana",
    "Porta con te uno snack sano fuori casa",
    "Aggiungi una nuova verdura alla tua dieta",
  ],
  pelle: [
    "Applica crema idratante mattina e sera",
    "Bevi acqua regolarmente durante il giorno",
    "Usa protezione solare",
    "Detergi il viso mattina e sera",
    "Mangia cibi ricchi di antiossidanti",
    "Evita di toccarti il viso",
    "Dormi su una federa pulita",
    "Fai uno scrub delicato",
    "Applica una maschera idratante",
    "Limita l'esposizione allo stress",
    "Bevi un tè verde ricco di antiossidanti",
    "Cambia la federa del cuscino questa settimana",
    "Applica il contorno occhi prima di dormire",
    "Evita docce troppo calde che seccano la pelle",
    "Prenditi 5 minuti per un automassaggio al viso",
  ],
  equilibrio_mentale: [
    "Medita per 5 minuti al mattino",
    "Scegli un'attività qualsiasi (mangiare, camminare, lavarti i denti) e falla concentrandoti solo su di essa, senza distrazioni",
    "Scrivi una sola frase che racchiude come ti senti in questo momento",
    "Guardati allo specchio e dì 3 affermazioni positive su di te: una sul fisico, una sul carattere, una su un tuo traguardo",
    "Disconnettiti dai social per 2 ore",
    "Pratica la gratitudine",
    "Leggi qualcosa di ispirazionale",
    "Ascolta un podcast motivazionale",
    "Passa tempo nella natura",
    "Pratica il perdono verso te stesso",
    "Fai 3 respiri consapevoli prima di iniziare la giornata",
    "Scrivi una cosa che ti rende orgoglioso/a di te",
    "Concediti una pausa senza sensi di colpa",
    "Sorridi a te stesso/a allo specchio",
    "Condividi un pensiero con una persona di fiducia",
  ],
};

// Compiti di livello 2 (per chi e' nell'app da oltre 90 giorni), solo sul server: qui servono
// per poterli tradurre quando arrivano dal server.
export const TASK_TEMPLATES_LEVEL2: { [key: string]: string[] } = {
  "energia": [
    "Fai una camminata di 20 minuti al mattino, appena puoi, con la luce del giorno",
    "Metti la cosa più importante della giornata nel momento in cui ti senti più sveglio",
    "Alterna 50 minuti di lavoro e 10 di pausa vera, lontano dallo schermo",
    "Fai una colazione completa con proteine, cereali integrali e frutta",
    "Fai 3 pause attive da 1 minuto di movimento a ritmo vivace durante la giornata",
    "Bevi un bicchiere d'acqua prima di ogni caffè e tieni la bottiglia a portata di mano",
    "Passa 15 minuti all'aperto a metà giornata, anche con il cielo coperto",
    "Stacca dagli schermi per 20 minuti dopo pranzo e fai due passi",
    "Concludi la doccia con 30 secondi di acqua fresca",
    "Se senti un calo nel pomeriggio, concediti una pausa di 10-20 minuti lontano dal telefono",
    "Metti in ordine la scrivania prima di iniziare: uno spazio libero alleggerisce la mente",
    "Fai una passeggiata a passo svelto di 10 minuti prima di cena"
  ],
  "sonno": [
    "Vai a letto e alzati alla stessa ora anche nel fine settimana, con uno scarto di massimo 30 minuti",
    "Lascia il telefono a caricare fuori dalla camera e usa una sveglia normale",
    "Crea una routine serale di 3 gesti sempre uguali: luce soffusa, stretching, respiro lento",
    "Evita caffè e tè dopo le 14:00",
    "Cena almeno 2 ore prima di andare a dormire",
    "Sistema la camera per la notte: temperatura fresca, buio e silenzio",
    "Fai 10 minuti di respirazione lenta a letto, con l'espirazione più lunga dell'inspirazione",
    "Prendi un po' di luce naturale nelle prime due ore dopo il risveglio",
    "Scrivi i pensieri che ti girano in testa, poi chiudi il quaderno e lasciali lì per stanotte",
    "Spegni gli schermi luminosi nell'ultima ora e usa una luce calda e un'attività tranquilla",
    "Fai uno stretching dolce di 5 minuti prima di coricarti",
    "Se hai bisogno di un riposino, fallo breve e non dopo le 15:00"
  ],
  "stress": [
    "Scrivi cosa ti preoccupa oggi e dividilo in \"posso agire\" e \"non dipende da me\"",
    "Fai 5 minuti di respirazione con espirazione lunga: inspira contando 4, espira contando 6",
    "Fai una camminata di 20 minuti senza telefono",
    "Di' no con gentilezza a una richiesta che oggi non è necessaria",
    "Pianifica una pausa vera a metà giornata e proteggila come un appuntamento",
    "Dedica 15 minuti a qualcosa che ti piace, senza uno scopo preciso",
    "Racconta com'è andata la giornata a una persona con cui stai bene",
    "Fai una sola cosa alla volta per un'ora, senza notifiche",
    "Controlla e rilassa spalle, mandibola e mani 3 volte durante la giornata",
    "Prepara la giornata di domani in 10 minuti, la sera prima",
    "Fai 5 minuti di stretching lento per collo e spalle",
    "Ripensa a 3 cose che sono andate bene oggi, anche piccole"
  ],
  "movimento": [
    "Cammina per 30 minuti a passo sostenuto",
    "Fai 3 serie da 12 squat con 1 minuto di pausa tra una serie e l'altra",
    "Fai 15 minuti di esercizi a corpo libero: squat, affondi e plank",
    "Fai una passeggiata o una pedalata di 40 minuti all'aperto",
    "Dedica 10 minuti alla mobilità di spalle, anche e schiena",
    "Sali le scale per almeno 5 piani durante la giornata, a passo tuo",
    "Fai 3 plank da 20-30 secondi con una pausa in mezzo",
    "Raggiungi 8000 passi oggi, anche a pezzetti durante la giornata",
    "Muoviti per 15 minuti con una canzone dopo l'altra, senza fermarti",
    "Allunga le gambe per 5 minuti dopo ogni camminata",
    "Alzati e muoviti per 2 minuti ogni ora di lavoro seduto",
    "Fai una sessione di 20 minuti a intensità media: bici, camminata in salita o corsa lenta"
  ],
  "alimentazione": [
    "Prepara in anticipo il pranzo di domani: verdura, proteine e cereali integrali",
    "Aggiungi legumi a un pasto: ceci, lenticchie o fagioli",
    "Porta in tavola 5 colori diversi di frutta e verdura oggi",
    "Mangia lentamente: posa le posate tra un boccone e l'altro per metà del pasto",
    "Sostituisci un prodotto confezionato con uno fresco o preparato da te",
    "Leggi l'etichetta di 3 prodotti che compri e scegli quello con meno ingredienti",
    "Fai la spesa con una lista che includa almeno 3 verdure diverse",
    "Cucina un pasto a base di pesce o legumi al posto della carne rossa",
    "Bevi acqua durante la giornata fino a 1,5-2 litri complessivi",
    "Fai una colazione senza zuccheri aggiunti",
    "Scegli la frutta intera al posto del succo",
    "Cena con verdure cotte e una fonte di proteine, senza appesantirti"
  ],
  "pelle": [
    "Bevi acqua con regolarità e tieni una bottiglia sempre a vista",
    "Aggiungi frutta o verdura colorata a ogni pasto di oggi",
    "Dormi almeno 7 ore stanotte: il sonno si vede anche sulla pelle",
    "Proteggiti dal sole nelle ore più calde: ombra, cappello e occhiali",
    "Mangia una porzione di pesce azzurro o una manciata di frutta secca",
    "Lava il viso con acqua tiepida, non calda, e asciugalo tamponando",
    "Cambia la federa del cuscino e l'asciugamano del viso",
    "Fai 10 minuti di respirazione lenta: anche lo stress si vede sulla pelle",
    "Riduci zuccheri aggiunti e fritti per tutta la giornata",
    "Passa 15 minuti all'aperto con un po' di luce, senza scottarti",
    "Evita di toccare e spremere il viso per tutta la giornata",
    "Fai una camminata a passo svelto: muoversi fa bene anche alla pelle"
  ],
  "equilibrio_mentale": [
    "Stai in silenzio per 10 minuti osservando il respiro e i pensieri senza giudicarli",
    "Scrivi tre cose per cui sei grato oggi e perché",
    "Fai una cosa alla volta con piena attenzione: mangiare, camminare o lavare i piatti senza distrazioni",
    "Disconnettiti dai social per mezza giornata",
    "Dì a una persona cara qualcosa di vero che apprezzi in lei",
    "Rivedi una cosa difficile di questa settimana e chiediti cosa ti ha insegnato",
    "Fai una camminata di 20 minuti nel verde osservando 5 cose che di solito non noti",
    "Concediti un'ora senza obiettivi né produttività",
    "Scegli una cosa che stai rimandando e dedicale 10 minuti",
    "Scrivi una lettera gentile a te stesso, come la scriveresti a un amico",
    "Fai 5 minuti di respirazione consapevole prima di rispondere a un messaggio difficile",
    "Racconta una tua difficoltà a qualcuno e ascolta la sua senza cercare soluzioni"
  ]
};

// Compiti generici usati dal server quando nessuna area e' riconosciuta
export const GENERIC_FALLBACK_TASKS: string[] = [
  "Fai 5 minuti di respirazione lenta (4-6) oggi.",
  "Fai una camminata di 10 minuti a passo comodo.",
  "Bevi 1 bicchiere d'acqua in più oggi.",
  "Spegni gli schermi 30 minuti prima di dormire.",
  "Fai 2 minuti di stretching collo/spalle.",
  "Mangia una porzione di verdura oggi.",
  "Scrivi 3 cose positive della giornata.",
  "Fai una pausa di 5 minuti senza schermi.",
  "Pratica la gratitudine per 2 minuti.",
  "Vai a letto alla stessa ora stasera."
];
